version: 0.9.5.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: LatticeObjectTree.NUnit\bin\Release\LatticeObjectTree.NUnit.dll
- path: LatticeObjectTree.NUnit\bin\Release\LatticeObjectTree.NUnit.XML